-- Fix ExpenseCategory: expand then shrink to new set
ALTER TABLE `expenses` MODIFY COLUMN `category` ENUM('SOFTWARE','HARDWARE','MARKETING','TRAVEL','SALARIES','OFFICE','OPERATIONS','PROJECT','OTHER') NOT NULL;
UPDATE `expenses` SET `category` = 'OTHER' WHERE `category` IN ('PROJECT','OPERATIONS');
ALTER TABLE `expenses` MODIFY COLUMN `category` ENUM('SOFTWARE','HARDWARE','MARKETING','TRAVEL','SALARIES','OFFICE','OTHER') NOT NULL;

-- Fix BudgetCategory: expand then shrink to new set
ALTER TABLE `budgets` MODIFY COLUMN `category` ENUM('MARKETING','DEVELOPMENT','OPERATIONS','SALES','HUMAN_RESOURCES','PROJECT','GENERAL','OTHER') NOT NULL;
UPDATE `budgets` SET `category` = 'OTHER' WHERE `category` IN ('PROJECT','GENERAL');
ALTER TABLE `budgets` MODIFY COLUMN `category` ENUM('MARKETING','DEVELOPMENT','OPERATIONS','SALES','HUMAN_RESOURCES','OTHER') NOT NULL;

-- Fix InvoiceStatus: add CANCELLED
ALTER TABLE `invoices` MODIFY COLUMN `status` ENUM('DRAFT','SENT','PAID','OVERDUE','CANCELLED') NOT NULL DEFAULT 'DRAFT';
ALTER TABLE `invoice_status_history` MODIFY COLUMN `oldStatus` ENUM('DRAFT','SENT','PAID','OVERDUE','CANCELLED') NULL;
ALTER TABLE `invoice_status_history` MODIFY COLUMN `newStatus` ENUM('DRAFT','SENT','PAID','OVERDUE','CANCELLED') NOT NULL;

-- Fix MilestoneStatus: add IN_PROGRESS
ALTER TABLE `milestones` MODIFY COLUMN `status` ENUM('PENDING','IN_PROGRESS','DONE') NOT NULL DEFAULT 'PENDING';

-- Fix CampaignStatus: add DRAFT
ALTER TABLE `campaigns` MODIFY COLUMN `status` ENUM('DRAFT','PLANNED','ACTIVE','PAUSED','COMPLETED') NOT NULL DEFAULT 'PLANNED';
